### ISSUE TITLE
The menu open/close on mobile and tablet is a bit laggy. Please make it smooth

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#21]

**Comment by ShkredovDmitriy** [comment]
done

**Comment by lpissinali** [comment]
It got faster now but it's still not smooth. Please check https://www.cssscript.com/demo/sliding-push-navigation-menu-pure-css/ on your phone, they have it pretty smooth
