### ISSUE TITLE
when you open the page both fields should show the "edit" version and the fields are not editable (so also dont show the courser that indicates that you can edit it). When you click edit, you can edit it and the "save" buttons shows. When you click save, the popup opens

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#223]
![image](https://user-images.githubusercontent.com/1376815/81477795-eb6f5080-9219-11ea-81ca-9815a3851373.png)

**Comment by lpissinali** [comment]
Phone fields should only accept numbers and the + symbol
and the bug below
![image](https://user-images.githubusercontent.com/1376815/81578263-d83fba80-93aa-11ea-8d7c-c355b4393331.png)

**Comment by lpissinali** [comment]
Also password field should show ****
![image](https://user-images.githubusercontent.com/1376815/81578407-0c1ae000-93ab-11ea-829c-d8de1359f95e.png)

**Comment by lpissinali** [comment]
Same issues on account page

**Comment by donrus** [comment]
fixed

**Comment by lpissinali** [comment]
I still have the error message over the dropdown

![image](https://user-images.githubusercontent.com/1376815/81693099-b48a7c00-945f-11ea-8143-7db03e4102db.png)
