### ISSUE TITLE
Add animations

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#87]
Please add animations on FAQ, Teams and Pressroom similar to the ones we have on the home page where the blocks fade in as the user scroll.

The FAQ has some more specific animations as shown on the video I sent

.

**Comment by ShkredovDmitriy** [comment]
Done.

**Comment by lpissinali** [comment]
Good job on the animations but still missing a little detail. On FAQ, when the user hover over the + the circle should increase size as it shows on the video.
![image](https://user-images.githubusercontent.com/1376815/80472003-76ac3480-8944-11ea-851e-4ef925152a6f.png)
